name: Tests contribution project CI

on:
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: unbuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
